export const countries = {
    'ANY': 'Random Countries',
    'AU': 'Australia',
    'BR': 'Brazil',
    'CA': 'Canada',
    'CH': 'Switzerland',
    'DE': 'Germany',
    'DK': 'Denmark',
    'ES': 'Spain',
    'FI': 'Finland',
    'FR': 'France',
    'GB': 'United Kingdom (UK)',
    'IE': 'Ireland',
    'IN': 'India',
    'IR': 'Iran',
    'MX': 'Mexico',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NZ': 'New Zealand',
    'RS': 'Serbia',
    'TR': 'Turkey',
    'UA': 'Ukraine',
    'US': 'United States (USA)'
}