export const countries = [
    { value: 'ANY', text: 'Random Countries' },
    { value: 'AU', text: 'Australia' },
    { value: 'BR', text: 'Brazil' },
    { value: 'CA', text: 'Canada' },
    { value: 'CH', text: 'Switzerland' },
    { value: 'DE', text: 'Germany' },
    { value: 'DK', text: 'Denmark' },
    { value: 'ES', text: 'Spain' },
    { value: 'FI', text: 'Finland' },
    { value: 'FR', text: 'France' },
    { value: 'GB', text: 'United Kingdom (UK)' },
    { value: 'IE', text: 'Ireland' },
    { value: 'IN', text: 'India' },
    { value: 'IR', text: 'Iran' },
    { value: 'MX', text: 'Mexico' },
    { value: 'NL', text: 'Netherlands' },
    { value: 'NO', text: 'Norway' },
    { value: 'NZ', text: 'New Zealand' },
    { value: 'RS', text: 'Serbia' },
    { value: 'TR', text: 'Turvalue' },
    { value: 'UA', text: 'Ukraine' },
    { value: 'US', text: 'United States (USA)' }
]